# This is a basic workflow to help you get started with Actions

name: Build Electron

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          
      - name: Install Dependencies
        run:  npm install --no-optional
          
      - name: rebuild Electron
        run: |
             npm install -g node-gyp
             npm rebuild --runtime=electron --target=12.0.5 --disturl=https://atom.io/download/atom-shell --abi=87    
             node-gyp rebuild

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: build # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./build/*
